name: infrastructure

services:

  elasticsearch:
    restart: always
    environment:
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      
  kibana:
    restart: always
    volumes:
      - ./elk/kibana/config/:/usr/share/kibana/config:ro
    ports: 
      - "5601:5601"
      
  sql-server-db:
    restart: always
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
      
  grafana:
    restart: always
    ports:
      - "3000:3000"
 
  prometheus:
    restart: always
    ports:
      - "9090:9090"

  rabbitmq:
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
    volumes: 
      - ./rabbitmq/etc/:/etc/rabbitmq/
      # - ./rabbitmq/data:/var/lib/rabbitmq/
      # - ./rabbitmq/logs:/var/log/rabbitmq/log

  redis:
    restart: always
    ports:
      - "6379:6379"

  # mongodb:
  #   restart: always
  #   hostname: mongodb
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./mongodb/mongod.conf:/etc/mongod.conf
  #     - ./mongodb/home/mongodb:/home/mongodb
  #     - ./mongodb/initdb.d/:/docker-entrypoint-initdb.d/
  #     # - ./mongodb/data/db/:/data/db
  #     - ./mongodb/data/log/:/var/log/mongodb/
  #   # environment:
  #     # MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #     # MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
  #   ports:
  #     - "27017:27017"
  #   command: ["-f", "/etc/mongod.conf"]

  # mongo-express:
  #   restart: always
  #   ports:
  #       - 8081:8081
  #   volumes:
  #       - ./mongo-express/docker-entrypoint.sh:/docker-entrypoint.sh
  #   env_file:
  #       - .env
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #     ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
  #     ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
  #   depends_on:
  #     - mongodb